constants:
  file:
    directory: D:\msfile\backand\upload

spring:
  application:
    name: gallery
  datasource:
    url: jdbc:mariadb://localhost/gallery
    username: root
    password: green502
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml